name: Deploy
on: 
  push:
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Publish
      run: |
              cd dist
              ln -s index.html 404.html
              git config --global user.email "lexus.hc293@gmail.com"
              git config --global user.name "HuanPT"
              git init
              git add -A
              git commit -m 'Deploy'
              git push -f https://HuanPT:${{ secrets.GITHUB_TOKEN }}@github.com/HuanPT/project.git master:gh-pages
